using System;
using System.Globalization;
using System.IO;
using System.Numerics;

public static class TouchstoneWriter
{
    // Touchstone header (RI = Real/Imag)
    // # <freq unit> <parameter> <format> R <ref impedance>
    private const double DefaultR = 50.0;

    public static void WriteS1P(
        string filePath,
        double[] freqsHz,
        Complex[] s11,
        double referenceOhms = DefaultR)
    {
        ValidateSameLength(freqsHz, s11);

        var ci = CultureInfo.InvariantCulture;

        using var sw = new StreamWriter(filePath, false);
        sw.WriteLine("! Generated by S-Parameter Tool");
        sw.WriteLine($"# Hz S RI R {referenceOhms.ToString(ci)}");

        for (int i = 0; i < freqsHz.Length; i++)
        {
            // freq  Re(S11)  Im(S11)
            sw.WriteLine(string.Format(ci, "{0} {1} {2}",
                freqsHz[i],
                s11[i].Real,
                s11[i].Imaginary));
        }
    }

    public static void WriteS2P(
        string filePath,
        double[] freqsHz,
        Complex[] s21,
        Complex[] s11 = null,
        Complex[] s12 = null,
        Complex[] s22 = null,
        double referenceOhms = DefaultR)
    {
        ValidateSameLength(freqsHz, s11);
        ValidateSameLength(freqsHz, s21);

        // Write zeros for missing parameters
        Complex[] s11Arr = s11 ?? CreateZeros(freqsHz.Length);
        Complex[] s12Arr = s12 ?? CreateZeros(freqsHz.Length);
        Complex[] s22Arr = s22 ?? CreateZeros(freqsHz.Length);

        var ci = CultureInfo.InvariantCulture;

        using var sw = new StreamWriter(filePath, false);
        sw.WriteLine("! Generated by VNA Tool");
        if (s12 is null || s22 is null)
            sw.WriteLine("! NOTE: S12 and/or S22 not measured -> written as 0");

        sw.WriteLine($"# Hz S RI R {referenceOhms.ToString(ci)}");

        for (int i = 0; i < freqsHz.Length; i++)
        {
            sw.WriteLine(string.Format(ci, "{0} {1} {2} {3} {4} {5} {6} {7} {8}",
                freqsHz[i],
                s11[i].Real, s11[i].Imaginary,
                s21[i].Real, s21[i].Imaginary,
                s12Arr[i].Real, s12Arr[i].Imaginary,
                s22Arr[i].Real, s22Arr[i].Imaginary));
        }
    }

    private static void ValidateSameLength(double[] freqs, Complex[] data)
    {
        if (freqs.Length != data.Length)
            throw new ArgumentException($"Längen passen nicht: freqs={freqs.Length}, data={data.Length}");
    }

    private static Complex[] CreateZeros(int n)
    {
        var arr = new Complex[n];
        for (int i = 0; i < n; i++) arr[i] = Complex.Zero;
        return arr;
    }
}
